### ISSUE TITLE
Example!

### ISSUE THREAD

**Issue by onuryurtturk** [juliand665/Bitmap#1]
Please provide some example usage of bitmap

**Comment by juliand665** [comment]
There's a quick example in the readme, as well as some illustrative unit tests. I'll add a link to those in the readme too.

**Comment by onuryurtturk** [comment]
@juliand665 I got another question. I'm working on uiimage pixels. I need to convert image to a hexadecimal value. When I try to get a color code of specific pixel on uiimage  I got the wrong value. In java I'm using bitmap.getpixel() method to reach pixel color and I'm getting correct value which is 255 but on swift same image pixel returning 0. Do you have any comment on this? or Is there a convenient way to convert image to a hexadecimal string?

**Comment by juliand665** [comment]
Can you share the relevant bits of code, perhaps in a gist? That would help me debug it.

As for hexadecimal colors, you could easily combine the values with some bitwise operations. I've just gone ahead and added [some convenient conversion methods](https://github.com/juliand665/Bitmap/blob/master/Sources/Bitmap/Utility/Pixel%2BHex.swift), so if you switch to the master branch rather than the latest release, you should be able to use these.

**Comment by onuryurtturk** [comment]
Here my codes. In Android I got int value (255) for position (x:0,y:0) but swift returns 0. Therefore I 'm getting useless image string 


```sh
private func createPrintableObject (img:UIImage) -> String{
        let sb = StringBuilder()
        let height:Int = Int(img.size.height)
        let width:Int = Int(img.size.width)
        var index = 0
        var rgb:Int,red:Int,green:Int,blue:Int
        var rgbColor:UIColor
        var auxBinaryChar: [Character] = ["0","0","0","0","0","0","0","0"]
        widthBytes = width / 8
        if(width % 8 > 0){
            widthBytes = ((Int)(width/8))+1
        }else{
            widthBytes = width / 8
        }
        self.total = widthBytes * height
        let pixelData = img.cgImage!.dataProvider!.data
        let data: UnsafePointer<UInt8> = CFDataGetBytePtr(pixelData)
        
        for h in 0...height-1 {
            for w in 0...width-1 {
                let value = Int(data[((width * w) + h) * 4])
                red = (value >> 16) & 0x000000FF
                green = (value >> 8) & 0x000000FF
                blue = (value) & 0x000000FF

                let totalColor = red + green + blue
                var auxChar = "1"
                if(totalColor > self.blackLimit){
                    auxChar = "0"
                }
                auxBinaryChar[index] = auxChar[0]
                index+=1
                if(index == 8 || w == (width-1)){
                    sb.append(self.fourByteBinary(binaryStr: String(auxBinaryChar)))
                    auxBinaryChar = ["0","0","0","0","0","0","0","0"]
                    index = 0
                }
            }
            sb.append("\n")
        }

        return sb.toString()

    }



 private func fourByteBinary(binaryStr:String) -> String{
        var decimal:Int = Int(binaryStr,radix: 2) ?? 0
        if(decimal > 15){
            return String(decimal, radix: 16, uppercase: true)
        }else{
           decimal = Int(String(decimal),radix:16) ?? 0
            return "0" + String(decimal, radix: 16, uppercase: true)
        }
    }
```

**Comment by onuryurtturk** [comment]
This is my useless swift result image. I can't find where I am wrong. Also I added my Java code at the end. It's working with no issue printing result is fine.

We know that 0 as rgb value is "Black" and 255 is "white". My image's first pixel is white but returning black (0).

![Test2](https://user-images.githubusercontent.com/5616467/79438762-a2422d00-7fdc-11ea-980b-2f039b8784c9.png)


```sh
 private String createPrintableObject(Bitmap bitmapImage) {
        StringBuilder sb = new StringBuilder();
        int height = bitmapImage.getHeight();
        int width = bitmapImage.getWidth();
        int rgb, red, green, blue, index = 0;
        char auxBinaryChar[] = {'0', '0', '0', '0', '0', '0', '0', '0'};
        widthBytes = width / 8;
        if (width % 8 > 0) {
            widthBytes = (((int) (width / 8)) + 1);
        } else {
            widthBytes = width / 8;
        }
        this.total = widthBytes * height;
        for (int h = 0; h < height; h++) {
            for (int w = 0; w < width; w++) {
                rgb = bitmapImage.getPixel(w, h);
                red = (rgb >> 16) & 0x000000FF;
                green = (rgb >> 8) & 0x000000FF;
                blue = (rgb) & 0x000000FF;
                char auxChar = '1';
                int totalColor = red + green + blue;
                if (totalColor > blackLimit) {
                    auxChar = '0';
                }
                auxBinaryChar[index] = auxChar;
                index++;
                if (index == 8 || w == (width - 1)) {
                    sb.append(fourByteBinary(new String(auxBinaryChar)));
                    auxBinaryChar = new char[]{'0', '0', '0', '0', '0', '0', '0', '0'};
                    index = 0;
                }
            }
            sb.append("\n");
        }
        return sb.toString();
    }

```

**Comment by juliand665** [comment]
Did you use some sort of java-to-swift conversion tool? I've never seen swift code quite like this…
For starters, `StringBuilder`s really aren't a thing in swift; you just create a string and append to it. Typecasts aren't `(Type) value` but instead `value as! Type`; i'm honestly astounded `(Int)(width/8)` somehow actually compiles.
I also don't see how you're generating an image from this code; it seems to me like it does the opposite: converting an image to a string.
